export CUDA_VISIBLE_DEVICES=1

model_name=DRFormer

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id ECL_96_96 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --batch_size 16 \
  --itr 10 \
  --patch_len 16 \
  --stride 4 \
  --sequence_num 3\
  --update_frequency 0.2 \
  --learnable_mask_epoches 0.5 \
  --sparsity 0.3 \
  --death_mode 'magnitude' \
  --learning_rate 0.001

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id ECL_96_192 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --batch_size 16 \
  --itr 10 \
  --patch_len 16 \
  --stride 4 \
  --sequence_num 3\
  --update_frequency 0.2 \
  --learnable_mask_epoches 0.5 \
  --sparsity 0.3 \
  --death_mode 'magnitude' \
  --learning_rate 0.001

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id ECL_96_336 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --batch_size 16 \
  --itr 10 \
  --patch_len 16 \
  --stride 4 \
  --sequence_num 3\
  --update_frequency 0.2 \
  --learnable_mask_epoches 0.5 \
  --sparsity 0.3 \
  --death_mode 'magnitude' \
  --learning_rate 0.001

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id ECL_96_720 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --batch_size 16 \
  --itr 10 \
  --patch_len 16 \
  --stride 4 \
  --sequence_num 3\
  --update_frequency 0.2 \
  --learnable_mask_epoches 0.5 \
  --sparsity 0.3 \
  --death_mode 'magnitude' \
  --learning_rate 0.001